# Release build script

trigger: none
pr: none

pool:
  vmImage: ubuntu-16.04

steps:
  - bash: |
      sudo npm install -g vsce

      PACKAGE_VERSION=$(cat secotron-color-theme/version.txt)

      vsce publish -p $MARKET_KEY --packagePath secotron-color-theme/secotron-color-theme-$PACKAGE_VERSION.vsix
    workingDirectory: '$(System.DefaultWorkingDirectory)/secotron.secotron-color-theme'
    displayName: Deploy
    env:
      MARKET_KEY: $(vscekey)
